#!/usr/bin/env python

# -*- coding: utf-8 -*-

# Author: Milan Nikolic <gen2brain@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
if os.path.isdir(os.path.join(".","src")) and os.path.isfile(os.path.join(".","setup.py")):
    from src.mixerapp import MixersApplication
    from src.voltisession import VoltiSession
else:
    from voltilite.mixerapp import MixersApplication
    from voltilite.voltisession import VoltiSession

if __name__ == "__main__":
    dbus = VoltiSession("com.google.code.VoltiLiteMixer")

    if ( dbus.check() ):
        sys.stderr.write("Only one instance is allowed\nExiting\n")
        sys.exit(1)
    else:
        mixer = MixersApplication()
        mixer.run()
