.TH voltilite 1
.SH NAME
\fBvoltilite\fP \- Tray Audio Volume Control

.SH SYNOPSIS
.B voltilite
.SH DESCRIPTION
\fBvoltilite\fP is an GTK+ application for controlling audio volume from system tray/notification area.
.SH DEPENDENCIES
.B Required:
.TP
\fBpygtk\fP 2.16.0 or later
.TP
\fBpyalsaaudio\fP 0.6 or later
.TP
\fBdbus-python\fP 0.80.0 or later

.SH BUGS
.TP
Please submit bug reports at:
.TP
\fIhttps://github.com/zerkalica/voltilite/issues\fP
.SH SEE ALSO
.BR voltilite-mixer (1)
.TP
Homepage: \fIhttps://github.com/zerkalica/voltilite\fP
.SH AUTHOR
Stefan Zerkalica <\fIzerkalica@gmail.com\fP>
Milan Nikolic <\fIgen2brain@gmail.com\fP>
